# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-binary:
    strategy:
      matrix:
        os: [linux, windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-pkg-cache: true

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: amd64
      run: go build -o go-mbslave-api-${{matrix.os}} -v

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: go-mbslave-api
        path: ./go-mbslave-api-${{matrix.os}}

        
  build-docker:
    needs: build-binary
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: go-mbslave-api:latest
        # Output a type=docker so we can load into docker.  
        # Alternative is type=oci which may be better but unknown to some users.
        outputs: type=docker,dest=/tmp/go-mbslave-api-image.tar
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: go-mbslave-api-container
        path: /tmp/go-mbslave-api-image.tar
      
      

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Set up test sqlite db
      run: | 
        sudo apt-get install -y sqlite3
        mkdir -p pkg/handlers/test/data
        sqlite3 pkg/handlers/test/data/test.db
        
    - name: Test
      run: go test -v ./...
      
